__all__ = [
    'fasterrcnn_custom_resnet', 
    'fasterrcnn_darknet',
    'fasterrcnn_efficientnet_b0',
    'fasterrcnn_efficientnet_b4',
    'fasterrcnn_mbv3_large',
    'fasterrcnn_mini_darknet_mini_head',
    'fasterrcnn_mini_darknet',
    'fasterrcnn_mobilenetv3_large_320_fpn',
    'fasterrcnn_mobilenetv3_large_fpn',
    'fasterrcnn_resnet18',
    'fasterrcnn_resnet50_fpn', 
    'fasterrcnn_resnet50', 
    'fasterrcnn_squeezenet1_0',
    'fasterrcnn_squeezenet1_1',
]